name: Build and Publish Storybook to GitHub Pages

on:
  push:
    branches:
      - 'dev'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: 'Deploy'
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js v18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn

      - id: build-publish
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.2
        with:
          install_command: yarn setup
          build_command: yarn build-storybook
          path: ./storybook-static
          checkout: false